# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  quick_colors: "" # select quick color schemes: "blue", "green", "orange", "pink", "purple", "red". If empty colors taken from _sass/ryancv/settings.scss
  dark_ui: 0 # activated dark ui styles
  rtl: 0 # activated rtl styles
  sidebar: 0 # for disable sidebar and sidebar button change to 0
  preloader: "loading..." # preloader loading text

buildings: 
  filters:
    - name: "All"
      slug: "box-item"
      active: 1

    - name: "Art Nouveau"
      slug: "f-nouveau"
      active: 0

    - name: "Louis XIII"
      slug: "f-louis"
      active: 0      

    - name: "Brutalist"
      slug: "f-brutalist"
      active: 0      

    - name: "Beaux-artes"
      slug: "f-beaux"
      active: 0    
      
    # - name: "Video"
    #   slug: "f-video"
    #   active: 0

    # - name: "Music"
    #   slug: "f-music"
    #   active: 0

    # - name: "Links"
    #   slug: "f-link"
    #   active: 0

    # - name: "Image"
    #   slug: "f-image"
    #   active: 0

    # - name: "Gallery"
    #   slug: "f-gallery"
    #   active: 0

    # - name: "Content"
    #   slug: "f-content"
    #   active: 0